name: bloodpressurelog
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #BASE
  sqflite: ^1.3.2+1
  basic_utils: ^2.6.3
  path_provider: ^1.6.24
  intl: ^0.16.1
  package_info: '>=0.4.3+2 <2.0.0'
  shared_preferences: '>=0.5.12+4 <2.0.0'

  #EXPORT/IMPORT
  pdf: ^1.11.2
  file_picker: ^1.8.0+1
  flutter_share: ^1.0.5

  #FIREBASE
  firebase_core: ^0.5.2
  firebase_analytics: ^6.2.0
  admob_flutter: ^1.0.1
  in_app_review: ^1.0.3
  url_launcher: ^5.7.10

  #UI
  intro_slider: ^2.3.3
  convex_bottom_bar: ^2.6.0
  fluttertoast: ^7.1.1
  rounded_loading_button: ^1.0.15
  step_progress_indicator: ^0.2.4+7
  numberpicker: ^1.2.1
  flutter_datetime_picker: ^1.4.0
  charts_flutter: ^0.9.0
  commons: ^0.7.8+3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  random_string: ^2.1.0
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "ddd9d9"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - lang/it.json
    - lang/en.json

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf